[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
LibOnnxRuntime = "edd8e961-822f-4801-b21c-cac5f01a00fa"

[sources]
LibOnnxRuntime = {rev = "ortchar", url = "https://github.com/IanET/LibOnnxRuntime.git"}
